"""Updated items table

Revision ID: 30a347116214
Revises: 81833d23696f
Create Date: 2025-02-19 21:41:17.124458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a347116214'
down_revision: Union[str, None] = '81833d23696f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('lot', sa.String(), nullable=False),
    sa.Column('pallet', sa.String(), nullable=False),
    sa.Column('roll', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
