"""Recreate item table

Revision ID: 6fdeba20c65d
Revises: 3a12da9cbfc6
Create Date: 2025-05-16 19:48:56.768893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdeba20c65d'
down_revision: Union[str, None] = '3a12da9cbfc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('lot', sa.String(), nullable=True),
    sa.Column('pallet', sa.String(), nullable=True),
    sa.Column('roll', sa.String(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
