"""Added ready flag to stock

Revision ID: 8fa58819a382
Revises: 30a347116214
Create Date: 2025-03-16 22:20:11.659637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa58819a382'
down_revision: Union[str, None] = '30a347116214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('ready', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'ready')
    # ### end Alembic commands ###
